.TH "src/main/java/frc/robot/Enums Directory Reference" 3 "Mon Jul 29 2019" "Version 1.0" "ENUM ROBOT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main/java/frc/robot/Enums Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBHatch\&.java\fP"
.br
.ti -1c
.RI "file \fBLift_Pistons\&.java\fP"
.br
.ti -1c
.RI "file \fBShift\&.java\fP"
.br
.in -1c
