.TH "frc.robot.subsystems.Hatch_Control" 3 "Mon Jul 29 2019" "Version 1.0" "ENUM ROBOT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.subsystems.Hatch_Control
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBTilt\fP (\fBHatch\fP hatch)"
.br
.ti -1c
.RI "static void \fBmainip\fP (\fBHatch\fP Manip)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file Hatch_Control\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void frc\&.robot\&.subsystems\&.Hatch_Control\&.mainip (\fBHatch\fP Manip)\fC [static]\fP"

.PP
Definition at line 30 of file Hatch_Control\&.java\&.
.SS "static void frc\&.robot\&.subsystems\&.Hatch_Control\&.Tilt (\fBHatch\fP hatch)\fC [static]\fP"

.PP
Definition at line 12 of file Hatch_Control\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ENUM ROBOT from the source code\&.
