.TH "frc.robot.Enums" 3 "Mon Jul 29 2019" "Version 1.0" "ENUM ROBOT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.Enums
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "enum \fBHatch\fP"
.br
.ti -1c
.RI "enum \fBLift_Pistons\fP"
.br
.ti -1c
.RI "enum \fBShift\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ENUM ROBOT from the source code\&.
