.TH "frc.robot" 3 "Mon Jul 29 2019" "Version 1.0" "ENUM ROBOT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot
.SH SYNOPSIS
.br
.PP
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBEnums\fP"
.br
.ti -1c
.RI "package \fBsubsystems\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMain\fP"
.br
.RI "Do NOT add any static variables to this class, or any initialization at all\&. "
.ti -1c
.RI "class \fBOI\fP"
.br
.RI "This class is the glue that binds the controls on the physical operator interface to the commands and command groups that allow control of the robot\&. "
.ti -1c
.RI "class \fBRobot\fP"
.br
.ti -1c
.RI "class \fBRobotMap\fP"
.br
.RI "The \fBRobotMap\fP is a mapping from the ports sensors and actuators are wired into to a variable name\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ENUM ROBOT from the source code\&.
