.TH "frc.robot.Enums.Lift_Pistons" 3 "Mon Jul 29 2019" "Version 1.0" "ENUM ROBOT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.Enums.Lift_Pistons
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBExtend\fP"
.br
.ti -1c
.RI "\fBRetract\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file Lift_Pistons\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "frc\&.robot\&.Enums\&.Lift_Pistons\&.Extend"

.PP
Definition at line 4 of file Lift_Pistons\&.java\&.
.SS "frc\&.robot\&.Enums\&.Lift_Pistons\&.Retract"

.PP
Definition at line 5 of file Lift_Pistons\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ENUM ROBOT from the source code\&.
