.TH "frc.robot.OI" 3 "Mon Jul 29 2019" "Version 1.0" "ENUM ROBOT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.OI \- This class is the glue that binds the controls on the physical operator interface to the commands and command groups that allow control of the robot\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static PowerDistributionPanel \fBpdp\fP = new PowerDistributionPanel(\fBRobotMap\&.pdpCAN\fP)"
.br
.ti -1c
.RI "static Joystick \fBcontroller1\fP = new Joystick(\fBRobotMap\&.controllerOnePort\fP)"
.br
.ti -1c
.RI "static Joystick \fBcontroller2\fP = new Joystick(\fBRobotMap\&.controllerTwoPort\fP)"
.br
.ti -1c
.RI "static WPI_TalonSRX \fBleftFrontDriveMotor\fP = new WPI_TalonSRX(\fBRobotMap\&.leftFrontDriveCAN\fP)"
.br
.ti -1c
.RI "static WPI_TalonSRX \fBleftCenterDriveMotor\fP = new WPI_TalonSRX(\fBRobotMap\&.leftCenterDriveCAN\fP)"
.br
.ti -1c
.RI "static WPI_TalonSRX \fBleftBackDriveMotor\fP = new WPI_TalonSRX(\fBRobotMap\&.leftBackDriveCAN\fP)"
.br
.ti -1c
.RI "static WPI_TalonSRX \fBrightFrontDriveMotor\fP = new WPI_TalonSRX(\fBRobotMap\&.rightFrontDriveCAN\fP)"
.br
.ti -1c
.RI "static WPI_TalonSRX \fBrightCenterDriveMotor\fP = new WPI_TalonSRX(\fBRobotMap\&.rightCenterDriveCAN\fP)"
.br
.ti -1c
.RI "static WPI_TalonSRX \fBrightBackDriveMotor\fP = new WPI_TalonSRX(\fBRobotMap\&.rightBackDriveCAN\fP)"
.br
.ti -1c
.RI "static DoubleSolenoid \fBfrontStilt\fP = new DoubleSolenoid(14, 2, 3)"
.br
.ti -1c
.RI "static DoubleSolenoid \fBbackStilt\fP = new DoubleSolenoid(14, 6, 7)"
.br
.ti -1c
.RI "static SpeedControllerGroup \fBleftDriveGroup\fP = new SpeedControllerGroup(\fBleftCenterDriveMotor\fP, \fBleftBackDriveMotor\fP,\fBleftFrontDriveMotor\fP)"
.br
.ti -1c
.RI "static SpeedControllerGroup \fBrightDriveGroup\fP = new SpeedControllerGroup(\fBrightCenterDriveMotor\fP, \fBrightBackDriveMotor\fP)"
.br
.ti -1c
.RI "static DifferentialDrive \fBdrive\fP = new DifferentialDrive(\fBleftDriveGroup\fP, \fBrightDriveGroup\fP)"
.br
.ti -1c
.RI "static Solenoid \fBshiftSolenoid\fP = new Solenoid(\fBRobotMap\&.PCMOneCAN\fP, RobotMap\&.shiftSolenoid)"
.br
.ti -1c
.RI "static Solenoid \fBhatchActuateSolenoid\fP = new Solenoid(\fBRobotMap\&.PCMOneCAN\fP, \fBRobotMap\&.hatchActuate\fP)"
.br
.ti -1c
.RI "static Solenoid \fBhatchTiltSolenoid\fP = new Solenoid(\fBRobotMap\&.PCMOneCAN\fP, \fBRobotMap\&.hatchTilt\fP)"
.br
.ti -1c
.RI "static VictorSP \fBcargoArmActuateOne\fP = new VictorSP(\fBRobotMap\&.cargoArmActuateOnePWM\fP)"
.br
.ti -1c
.RI "static VictorSP \fBcargoClawLeft\fP = new VictorSP(\fBRobotMap\&.cargoClawLeftRotatePWM\fP)"
.br
.ti -1c
.RI "static VictorSP \fBcargoClawRight\fP = new VictorSP(\fBRobotMap\&.cargoClawRightRotatePWM\fP)"
.br
.ti -1c
.RI "static SpeedControllerGroup \fBcargoIntake\fP = new SpeedControllerGroup(\fBcargoClawLeft\fP, \fBcargoClawRight\fP)"
.br
.ti -1c
.RI "static DigitalInput \fBballLimit\fP = new DigitalInput(\fBRobotMap\&.ballLimitDIO\fP)"
.br
.ti -1c
.RI "static Accelerometer \fBaccelerometer\fP = new BuiltInAccelerometer(Accelerometer\&.Range\&.k4G)"
.br
.ti -1c
.RI "static Compressor \fBpressureSwitch\fP = new Compressor()"
.br
.ti -1c
.RI "static AnalogInput \fBPressureread\fP = new AnalogInput(\fBRobotMap\&.Pressure_read\fP)"
.br
.ti -1c
.RI "static ADXRS450_Gyro \fBBalance\fP = new ADXRS450_Gyro()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is the glue that binds the controls on the physical operator interface to the commands and command groups that allow control of the robot\&. 
.PP
Definition at line 30 of file OI\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "Accelerometer frc\&.robot\&.OI\&.accelerometer = new BuiltInAccelerometer(Accelerometer\&.Range\&.k4G)\fC [static]\fP"

.PP
Definition at line 61 of file OI\&.java\&.
.SS "DoubleSolenoid frc\&.robot\&.OI\&.backStilt = new DoubleSolenoid(14, 6, 7)\fC [static]\fP"

.PP
Definition at line 44 of file OI\&.java\&.
.SS "ADXRS450_Gyro frc\&.robot\&.OI\&.Balance = new ADXRS450_Gyro()\fC [static]\fP"

.PP
Definition at line 65 of file OI\&.java\&.
.SS "DigitalInput frc\&.robot\&.OI\&.ballLimit = new DigitalInput(\fBRobotMap\&.ballLimitDIO\fP)\fC [static]\fP"

.PP
Definition at line 60 of file OI\&.java\&.
.SS "VictorSP frc\&.robot\&.OI\&.cargoArmActuateOne = new VictorSP(\fBRobotMap\&.cargoArmActuateOnePWM\fP)\fC [static]\fP"

.PP
Definition at line 55 of file OI\&.java\&.
.SS "VictorSP frc\&.robot\&.OI\&.cargoClawLeft = new VictorSP(\fBRobotMap\&.cargoClawLeftRotatePWM\fP)\fC [static]\fP"

.PP
Definition at line 56 of file OI\&.java\&.
.SS "VictorSP frc\&.robot\&.OI\&.cargoClawRight = new VictorSP(\fBRobotMap\&.cargoClawRightRotatePWM\fP)\fC [static]\fP"

.PP
Definition at line 57 of file OI\&.java\&.
.SS "SpeedControllerGroup frc\&.robot\&.OI\&.cargoIntake = new SpeedControllerGroup(\fBcargoClawLeft\fP, \fBcargoClawRight\fP)\fC [static]\fP"

.PP
Definition at line 58 of file OI\&.java\&.
.SS "Joystick frc\&.robot\&.OI\&.controller1 = new Joystick(\fBRobotMap\&.controllerOnePort\fP)\fC [static]\fP"

.PP
Definition at line 33 of file OI\&.java\&.
.SS "Joystick frc\&.robot\&.OI\&.controller2 = new Joystick(\fBRobotMap\&.controllerTwoPort\fP)\fC [static]\fP"

.PP
Definition at line 34 of file OI\&.java\&.
.SS "DifferentialDrive frc\&.robot\&.OI\&.drive = new DifferentialDrive(\fBleftDriveGroup\fP, \fBrightDriveGroup\fP)\fC [static]\fP"

.PP
Definition at line 49 of file OI\&.java\&.
.SS "DoubleSolenoid frc\&.robot\&.OI\&.frontStilt = new DoubleSolenoid(14, 2, 3)\fC [static]\fP"

.PP
Definition at line 43 of file OI\&.java\&.
.SS "Solenoid frc\&.robot\&.OI\&.hatchActuateSolenoid = new Solenoid(\fBRobotMap\&.PCMOneCAN\fP, \fBRobotMap\&.hatchActuate\fP)\fC [static]\fP"

.PP
Definition at line 52 of file OI\&.java\&.
.SS "Solenoid frc\&.robot\&.OI\&.hatchTiltSolenoid = new Solenoid(\fBRobotMap\&.PCMOneCAN\fP, \fBRobotMap\&.hatchTilt\fP)\fC [static]\fP"

.PP
Definition at line 53 of file OI\&.java\&.
.SS "WPI_TalonSRX frc\&.robot\&.OI\&.leftBackDriveMotor = new WPI_TalonSRX(\fBRobotMap\&.leftBackDriveCAN\fP)\fC [static]\fP"

.PP
Definition at line 38 of file OI\&.java\&.
.SS "WPI_TalonSRX frc\&.robot\&.OI\&.leftCenterDriveMotor = new WPI_TalonSRX(\fBRobotMap\&.leftCenterDriveCAN\fP)\fC [static]\fP"

.PP
Definition at line 37 of file OI\&.java\&.
.SS "SpeedControllerGroup frc\&.robot\&.OI\&.leftDriveGroup = new SpeedControllerGroup(\fBleftCenterDriveMotor\fP, \fBleftBackDriveMotor\fP,\fBleftFrontDriveMotor\fP)\fC [static]\fP"

.PP
Definition at line 46 of file OI\&.java\&.
.SS "WPI_TalonSRX frc\&.robot\&.OI\&.leftFrontDriveMotor = new WPI_TalonSRX(\fBRobotMap\&.leftFrontDriveCAN\fP)\fC [static]\fP"

.PP
Definition at line 36 of file OI\&.java\&.
.SS "PowerDistributionPanel frc\&.robot\&.OI\&.pdp = new PowerDistributionPanel(\fBRobotMap\&.pdpCAN\fP)\fC [static]\fP"

.PP
Definition at line 31 of file OI\&.java\&.
.SS "AnalogInput frc\&.robot\&.OI\&.Pressureread = new AnalogInput(\fBRobotMap\&.Pressure_read\fP)\fC [static]\fP"

.PP
Definition at line 64 of file OI\&.java\&.
.SS "Compressor frc\&.robot\&.OI\&.pressureSwitch = new Compressor()\fC [static]\fP"

.PP
Definition at line 62 of file OI\&.java\&.
.SS "WPI_TalonSRX frc\&.robot\&.OI\&.rightBackDriveMotor = new WPI_TalonSRX(\fBRobotMap\&.rightBackDriveCAN\fP)\fC [static]\fP"

.PP
Definition at line 41 of file OI\&.java\&.
.SS "WPI_TalonSRX frc\&.robot\&.OI\&.rightCenterDriveMotor = new WPI_TalonSRX(\fBRobotMap\&.rightCenterDriveCAN\fP)\fC [static]\fP"

.PP
Definition at line 40 of file OI\&.java\&.
.SS "SpeedControllerGroup frc\&.robot\&.OI\&.rightDriveGroup = new SpeedControllerGroup(\fBrightCenterDriveMotor\fP, \fBrightBackDriveMotor\fP)\fC [static]\fP"

.PP
Definition at line 47 of file OI\&.java\&.
.SS "WPI_TalonSRX frc\&.robot\&.OI\&.rightFrontDriveMotor = new WPI_TalonSRX(\fBRobotMap\&.rightFrontDriveCAN\fP)\fC [static]\fP"

.PP
Definition at line 39 of file OI\&.java\&.
.SS "Solenoid frc\&.robot\&.OI\&.shiftSolenoid = new Solenoid(\fBRobotMap\&.PCMOneCAN\fP, RobotMap\&.shiftSolenoid)\fC [static]\fP"

.PP
Definition at line 51 of file OI\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ENUM ROBOT from the source code\&.
