.TH "frc.robot.subsystems.DriveTrain" 3 "Mon Jul 29 2019" "Version 1.0" "ENUM ROBOT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.subsystems.DriveTrain
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDriveTrain\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBshift\fP (\fBShift\fP direction)"
.br
.ti -1c
.RI "static void \fBperiodic\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file DriveTrain\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "frc\&.robot\&.subsystems\&.DriveTrain\&.DriveTrain ()"

.PP
Definition at line 12 of file DriveTrain\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void frc\&.robot\&.subsystems\&.DriveTrain\&.periodic ()\fC [static]\fP"

.PP
Definition at line 28 of file DriveTrain\&.java\&.
.SS "static void frc\&.robot\&.subsystems\&.DriveTrain\&.shift (\fBShift\fP direction)\fC [static]\fP"

.PP
Definition at line 15 of file DriveTrain\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ENUM ROBOT from the source code\&.
