.TH "frc.robot.subsystems.Cargo" 3 "Mon Jul 29 2019" "Version 1.0" "ENUM ROBOT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.subsystems.Cargo
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCargo\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBactuateArm\fP (double speed)"
.br
.ti -1c
.RI "static void \fBstopArm\fP ()"
.br
.ti -1c
.RI "static void \fBactuateClaw\fP (double speed)"
.br
.ti -1c
.RI "static void \fBstopClaw\fP ()"
.br
.ti -1c
.RI "static void \fBholdBall\fP ()"
.br
.ti -1c
.RI "static void \fBupdate\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static Timer \fBcargoTimer\fP = new Timer()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file Cargo\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "frc\&.robot\&.subsystems\&.Cargo\&.Cargo ()"

.PP
Definition at line 13 of file Cargo\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void frc\&.robot\&.subsystems\&.Cargo\&.actuateArm (double speed)\fC [static]\fP"

.PP
Definition at line 14 of file Cargo\&.java\&.
.SS "static void frc\&.robot\&.subsystems\&.Cargo\&.actuateClaw (double speed)\fC [static]\fP"

.PP
Definition at line 20 of file Cargo\&.java\&.
.SS "static void frc\&.robot\&.subsystems\&.Cargo\&.holdBall ()\fC [static]\fP"

.PP
Definition at line 26 of file Cargo\&.java\&.
.SS "static void frc\&.robot\&.subsystems\&.Cargo\&.stopArm ()\fC [static]\fP"

.PP
Definition at line 17 of file Cargo\&.java\&.
.SS "static void frc\&.robot\&.subsystems\&.Cargo\&.stopClaw ()\fC [static]\fP"

.PP
Definition at line 23 of file Cargo\&.java\&.
.SS "static void frc\&.robot\&.subsystems\&.Cargo\&.update ()\fC [static]\fP"

.PP
Definition at line 29 of file Cargo\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "Timer frc\&.robot\&.subsystems\&.Cargo\&.cargoTimer = new Timer()\fC [static]\fP"

.PP
Definition at line 8 of file Cargo\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ENUM ROBOT from the source code\&.
