.TH "frc.robot.subsystems.Stilts" 3 "Mon Jul 29 2019" "Version 1.0" "ENUM ROBOT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.subsystems.Stilts
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBactuateFront\fP (\fBLift_Pistons\fP \fBStilts\fP)"
.br
.ti -1c
.RI "static void \fBactuateBack\fP (\fBLift_Pistons\fP \fBStilts\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Nicholas Blackburn 
.RE
.PP
\fBSee also:\fP
.RS 4
Switch statemints for both Sets of \fBStilts\fP Lift_Pistons is an Enum set is a list for case statements 
.RE
.PP

.PP
Definition at line 12 of file Stilts\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void frc\&.robot\&.subsystems\&.Stilts\&.actuateBack (\fBLift_Pistons\fP Stilts)\fC [static]\fP"

.PP
Definition at line 28 of file Stilts\&.java\&.
.SS "static void frc\&.robot\&.subsystems\&.Stilts\&.actuateFront (\fBLift_Pistons\fP Stilts)\fC [static]\fP"

.PP
Definition at line 14 of file Stilts\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ENUM ROBOT from the source code\&.
