.TH "frc.robot.Enums.Hatch" 3 "Mon Jul 29 2019" "Version 1.0" "ENUM ROBOT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.Enums.Hatch
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBExtend\fP"
.br
.ti -1c
.RI "\fBRetract\fP"
.br
.ti -1c
.RI "\fBOpen\fP"
.br
.ti -1c
.RI "\fBClose\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file Hatch\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "frc\&.robot\&.Enums\&.Hatch\&.Close"

.PP
Definition at line 8 of file Hatch\&.java\&.
.SS "frc\&.robot\&.Enums\&.Hatch\&.Extend"

.PP
Definition at line 5 of file Hatch\&.java\&.
.SS "frc\&.robot\&.Enums\&.Hatch\&.Open"

.PP
Definition at line 7 of file Hatch\&.java\&.
.SS "frc\&.robot\&.Enums\&.Hatch\&.Retract"

.PP
Definition at line 6 of file Hatch\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ENUM ROBOT from the source code\&.
