.TH "frc.robot.subsystems.Teleop_Controller2" 3 "Mon Jul 29 2019" "Version 1.0" "ENUM ROBOT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.subsystems.Teleop_Controller2
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBTeleop2\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Nicholas Blackburn Button Maps for Operator controller Controller 2 (Operator controller) LeftBumper - Sucks in ball RightBumper - Throws ball LeftTrigger - closes hatch RightTrigger - opens hatch LeftStick - moves \fBCargo\fP arm Button X - Stop \fBCargo\fP arm 
.RE
.PP

.PP
Definition at line 20 of file Teleop_Controller2\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static void frc\&.robot\&.subsystems\&.Teleop_Controller2\&.Teleop2 ()\fC [static]\fP"
Funtion pulls ball into claw
.PP
Funtion fires ball into claw
.PP
Funtion opens hatch
.PP
Funtion Closes Hatch
.PP
Funtion Moves \fBCargo\fP Arm in Y axis
.PP
<Funtion Moves \fBCargo\fP Arm in Y axis
.PP
<Function kills \fBCargo\fP arm 
.PP
Definition at line 22 of file Teleop_Controller2\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ENUM ROBOT from the source code\&.
