.TH "frc.robot.Enums.Shift" 3 "Mon Jul 29 2019" "Version 1.0" "ENUM ROBOT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
frc.robot.Enums.Shift
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBHigh_Gear\fP"
.br
.ti -1c
.RI "\fBLow_Gear\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file Shift\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "frc\&.robot\&.Enums\&.Shift\&.High_Gear"

.PP
Definition at line 4 of file Shift\&.java\&.
.SS "frc\&.robot\&.Enums\&.Shift\&.Low_Gear"

.PP
Definition at line 5 of file Shift\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ENUM ROBOT from the source code\&.
